name: Feature suggestion
description: Submit requests for new features here
title: "[FEAT] Your title here"
labels: ["enhancement"]
assignees:
  - aclist
body:
  - type: dropdown
    id: device
    attributes:
      label: Device type
      options:
        - Desktop PC
        - Steam Deck
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: DZGUI version
    validations:
      required: true
      placeholder: "5.6.0"
  - type: input
    id: distro
    attributes:
      label: Linux distribution
    validations:
      required: true
      placeholder: "Arch Linux"
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the feature
      description: A clear and detailed description
      placeholder: "E.g., Add a dialog to the Options menu that automatically lets the user do Y"
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Describe the benefit
      description: How will this feature benefit large numbers of users?
      placeholder: "E.g., Currently, users have to manually do X to achieve Y. Implementing this feature would achieve A, B, and C."
    validations:
      required: true
