name: Troubleshooting
description: Submit user error/troubleshooting questions here
title: "[HELP] "
labels: ["troubleshooting"]
assignees:
  - aclist
body:
  - type: checkboxes
    id: kb
    attributes:
      label: Did you check if this issue already exists?
      options:
        - label: I have checked the [Knowledge Base](https://aclist.github.io/dzgui/kb.html) and searched through [past issues](https://github.com/aclist/dztui/issues?q=is%3Aissue+is%3Aclosed) and did not find my issue there. 
          required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: DZGUI version
      options:
        - 5.6.x (stable)
        - 5.7.x (testing)
        - Version prior to 5.6.0
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Device type
      options:
        - Desktop PC
        - Steam Deck
    validations:
      required: true
  - type: input
    id: distro
    attributes:
      label: Linux distribution
    validations:
      required: true
      placeholder: "Arch Linux"
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: A detailed description. What did you expect to happen?
      placeholder: "Include as much detail as possible and state the steps leading up to the problem. E.g., First I do this, then I do this, then this happens."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Additional log output
      description: Attach the file `$HOME/.local/state/dzgui/DZGUI_DEBUG.log` by clicking this area to highlight it and then dragging the file in.
    validations:
      required: false
