[[DZG-001, DZG-001]]
== DZG-001: Periodically getting dropped from servers, or servers appear unreachable
Last updated: {d}

It is a longstanding issue in DayZ that the game opens a large number of connections when querying servers and/or while connected to servers. This can result in excess traffic on the user's PC which, depending on how much headroom your network has, can lead to getting dropped, unresponsiveness, or a timeout.

If you are on Wi-Fi, try switching to a wired connection and see if the problem resolves itself. If it does, your wireless router settings do not have enough headroom for max simultaneous connections. Use a wired connection, or update your network settings to a more permissive setup.

Bohemia has acknowledged this issue going back 10+ years and stated that DayZ has a heavy impact on the network, but there is as yet no proposed solution on the DayZ side.

This issue is frequently seen on Steam Deck, due to the tendency for users to use it in an untethered Wi-Fi setup.
