update_mods = "Update mods and connect"
connect = "Connect"
back = "Back"
cancel = "Cancel"
warnings = "Warnings"
errors = "Errors"
mods = "Mods"
total_mods = "Total mods: "
all_updated = "All mods updated."
"If you recently installed {build} or moved it to a different drive, "
"restart Steam to allow these changes to synchronize, then try again."
